[versions]
springBoot = "3.5.7"
springDependecyManagement = "1.1.7"
kotlin = "2.0.0"
springSecurity = "6.5.6"
jjwt = "0.12.6"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springBoot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
spring-boot-security-test = { module = "org.springframework.security:spring-security-test", version.ref = "springSecurity" }
reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
jakarta-validation = { module = "jakarta.validation:jakarta.validation-api", version = "3.1.1" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version = "2.20.0" }
spring-boot-starter-data-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb", version.ref = "springBoot" }
spring-boot-starter-data-mongodb-reactive = { module = "org.springframework.boot:spring-boot-starter-data-mongodb-reactive", version.ref = "springBoot" }
kotlinx-coroutines-core = { module="org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.2" }
kotlinx-coroutines-test = { module="org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.10.2" }
kotlinx-coroutines-reactor = { module="org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version = "1.10.2" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "5.4.0" }
junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mongration = {module = "com.github.kuliginstepan:mongration", version = "2.0.1"}

jjwt-api = { group = "io.jsonwebtoken", name = "jjwt-api", version.ref = "jjwt" }
jjwt-impl = { group = "io.jsonwebtoken", name = "jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { group = "io.jsonwebtoken", name = "jjwt-jackson", version.ref = "jjwt" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "4.10.0" }


[plugins]
springframework-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependecy-management = { id = "io.spring.dependency-management", version.ref = "springDependecyManagement" }